#!/bin/ksh
# lemount - Luiz' extensions for mount
# This is a prototype made with Korn Shell, probabily i will rewrite this in Go.

root=/
dev=/dev
mnt=/mnt
mount_points=(dsk usb cdrom);
base_number='0'

main(){
	printf '%s' 'Creating mount points...' &
	for (( i=0; i<${#mount_points}; i++ )){
		test ! -e ${root}${mount_points[${i}]} && mkdir ${root}${mount_points[${i}]};
	}
	printf  '%s\n\n' 'done.'
	echo 'Available disks:';
	fdisk -l;
	printf '%s' 'Which disk do you want to mount? ';
	read disk;
	if echo $disk | grep '^loop'; then 
		disk_postfix='v';
	else
		disk_postfix='';
	fi
	printf '%s' 'What is it? [?] ';
	read type;
	if [[ ${type} == \? ]]; then
		echo ${mount_points[*]};
		read type;
	fi
	if [ ! -z `ls -A "${root}${type}/${base_number}${disk_postfix}" 2> /dev/null` ]; then
		while [ -e "${root}${type}/${base_number}${disk_postfix}" ]; do
			base_number=$(( base_number + 1 ));
		done
		mkdir -v "${root}${type}/${base_number}${disk_postfix}";
	fi
	test ! -e "${root}${type}/${base_number}${disk_postfix}" && mkdir -v "${root}${type}/${base_number}${disk_postfix}";
	mount -v "${dev}/${disk}" "${root}${type}/${base_number}${disk_postfix}" &&
	if [ -z `ls -A "${mnt}/${type}${base_number}${disk_postfix}" 2> /dev/null` ]; then
		ln -sv "${root}${type}/${base_number}${disk_postfix}" "${mnt}/${type}${base_number}${disk_postfix}";
	fi
	echo "${disk} was mounted succesfully at ${root}${type}/${base_number}${disk_postfix}.";
	exit 0;
}

main
